stages:
  merging:
    cmd: python3 src/data/make_dataset.py
    deps:
    - data/raw/2017.csv
    - data/raw/2018.csv
    - data/raw/2019.csv
    - src/data/make_dataset.py
    outs:
    - data/raw/FinaleBari.csv

  preprocessing:
    cmd: python3 src/data/preprocessing.py
    deps:
    - data/raw/FinaleBari.csv
    - src/data/preprocessing.py
    outs:
    - data/processed/GHI.csv
    - data/processed/PreprocessedData.csv
  split_dataset:
    cmd: python3 src/data/split_dataset.py
    deps:
    - data/processed/GHI.csv
    - data/processed/PreprocessedData.csv
    - src/data/split_dataset.py
    outs:
    - data/interim/split_train.csv
    - data/interim/split_test.csv
  Knr:
    cmd: python3 src/models/knr.py
    deps:
    - data/interim/split_train.csv
    - data/interim/split_test.csv
    - src/models/knr.py
    - src/models/train_model.py
    outs:
    - models/knr.pkl
    metrics:
    - models/knr.metrics
  XGBooster:
    cmd: python3 src/models/xgbooster.py
    deps:
    - data/interim/split_train.csv
    - data/interim/split_test.csv
    - src/models/xgbooster.py
    - src/models/train_model.py
    outs:
    - models/xgb.pkl
    metrics:
    - models/xgb.metrics
  LinearRegression:
    cmd: python3 src/models/linear_regressor.py
    deps:
    - data/interim/split_train.csv
    - data/interim/split_test.csv
    - src/models/linear_regressor.py
    - src/models/train_model.py
    outs:
    - models/linear.pkl
    metrics:
    - models/linear.metrics
  RandomForestRegressor:
    cmd: python3 src/models/random_forest_regressor.py
    deps:
    - data/interim/split_train.csv
    - data/interim/split_test.csv
    - src/models/random_forest_regressor.py
    - src/models/train_model.py
    outs:
    - models/randomForestRegressor.pkl
    metrics:
    - models/randomForestRegressor.metrics

  Compare:
    cmd: python3 src/models/compare.py
    deps:
    - models/randomForestRegressor.metrics
    - models/randomForestRegressor.pkl
    - models/linear.metrics
    - models/linear.pkl
    - models/xgb.metrics
    - models/xgb.pkl
    - models/knr.metrics
    - models/knr.pkl
    outs:
    - models/best_model.pkl
    metrics:
    - models/best_metrics.metrics