stages:
  merging:
    cmd: python3 src/data/make_dataset.py
    deps:
    - data/raw/2017.csv
    - data/raw/2018.csv
    - data/raw/2019.csv
    - src/data/make_dataset.py
    outs:
    - data/raw/FinaleBari.csv

  preprocessing:
    cmd: python3 src/data/preprocessing.py
    deps:
    - data/raw/FinaleBari.csv
    - src/data/preprocessing.py
    outs:
    - data/processed/GHI.csv
    - data/processed/PreprocessedData.csv
  split_dataset:
    cmd: python3 src/data/split_dataset.py
    deps:
    - data/processed/GHI.csv
    - data/processed/PreprocessedData.csv
    - src/data/split_dataset.py
    outs:
    - data/interim/x_train.csv
    - data/interim/y_train.csv
    - data/interim/x_test.csv
    - data/interim/y_test.csv
  Knr:
    cmd: python3 src/models/KNR.py
    deps:
    - data/interim/x_train.csv
    - data/interim/y_train.csv
    - data/interim/x_test.csv
    - data/interim/y_test.csv
    - src/models/KNR.py
    - src/models/train_model.py
    outs:
    - models/knr.pkl
  XGBooster:
    cmd: python3 src/models/XGBOOSTER.py
    deps:
    - data/interim/x_train.csv
    - data/interim/y_train.csv
    - data/interim/x_test.csv
    - data/interim/y_test.csv
    - src/models/XGBOOSTER.py
    - src/models/train_model.py
    outs:
    - models/xgb.pkl
  LinearRegression:
    cmd: python3 src/models/LinearRegression.py
    deps:
    - data/interim/x_train.csv
    - data/interim/y_train.csv
    - data/interim/x_test.csv
    - data/interim/y_test.csv
    - src/models/LinearRegression.py
    - src/models/train_model.py
    outs:
    - models/linear.pkl
  RandomForestRegressor:
    cmd: python3 src/models/RandomForestRegressor.py
    deps:
    - data/interim/x_train.csv
    - data/interim/y_train.csv
    - data/interim/x_test.csv
    - data/interim/y_test.csv
    - src/models/RandomForestRegressor.py
    - src/models/train_model.py
    outs:
    - models/randomForest.pkl

  Evaluate:
    cmd: python3 src/models/evaluate.py
    deps:
    - models/randomForest.pkl
    - models/linear.pkl
    - models/xgb.pkl
    - models/knr.pkl