name: Alibi-check

on:
  workflow_dispatch:

jobs:
  alibi-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements_actions.txt

      - uses: iterative/setup-dvc@v1
      
      - name: Pull data with DVC
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS }}
        run: |
          dvc pull

      - name: Run make_dataset
        run: python src/data/make_dataset.py
      
      - name: Run preprocessing
        run: python src/data/preprocessing.py

      - name: Run split_dataset
        run: python src/data/split_dataset.py

      - name: Run Alibi module
        run: python src/models/alibi/alibi.py
      
      - name: Configure git
        run: |
          git config --global user.email "f.didio2@studenti.uniba.it"
          git config --global user.name "Fra3005"
      
      - name: Add, commit and push changes
        run: |
          git add .
          git commit -m "Update drift_results"
          git push
