name: PreProcessing

on:
  workflow_dispatch:

jobs:
  Run-preprocessing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - uses: iterative/setup-dvc@v1
  
      - name: Pull data with DVC
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS }}
        run: |
          dvc pull

      - name: Run make_dataset
        run: python src/data/make_dataset.py
      
      - name: Run preprocessing
        run: python src/data/preprocessing.py

      - name: Run split_dataset
        run: python src/data/split_dataset.py