name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        pip install pylint
        pip install pytest
    - name: Analysing the code with pylint
      run: |
        pylint --fail-under=7 src/app/**
        pylint --fail-under=7 src/data/**
        pylint --fail-under=7 src/models/**
        pylint --fail-under=7 src/test/**  --ignore-path=src/test/training_test.py
