name: Testing module

on: 
  push:
    paths:
      - 'src/**'
      - '!src/app/**'

jobs:
  build:
    runs-on: macos-latest

  steps:
  - name: Checkout
    uses: actions/heckout@v4

  - name: Set Python
    uses: action/setup-python@v4
    with:
      python-version: '3.11'

  - name: Install dependencies
    run: pip install -r requirementes.txt

  - name: Preprocessing_test with Pytest
    run: pytest src/test/preprocessing_test.py

  - name: Training_test with Pytest
    run: pytest src/test/training_test.py

  - name: Compare_test with Pytest
    run: pytest src/test/compare_test.py

  
