name: Testing module

on: 
  push:
    paths:
      - 'src/**'
      - '!src/app/**'

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Preprocessing_test with Pytest
      run: pytest src/test/preprocessing_test.py --file data/raw/FinaleBari.csv

    - name: Training_test with Pytest
      run: pytest src/test/training_test.py

    - name: Compare_test with Pytest
      run: pytest src/test/compare_test.py

  
